name: Build and publish
run-name: ${{ github.actor }} 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: get pack
      run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.33.2/pack-v0.33.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

    - name: build
      run: |-
        pack build ghcr.io/jonasasx/terraform-registry-mirror:0.0.1 \
        --path ./  \
        --builder gcr.io/paketo-buildpacks/builder:base \
        --publish